# Generated by Django 5.0.6 on 2024-06-14 06:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_attendance_status', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Статус посещение',
                'verbose_name_plural': 'Статусы посещения',
                'db_table': 'attendance_status',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=45)),
                ('slug_status', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=55, verbose_name='Телефон')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_branches', to=settings.AUTH_USER_MODEL, verbose_name='Админ филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_audience', models.CharField(max_length=45)),
                ('capacity', models.CharField(max_length=45)),
                ('slug_audience', models.CharField(max_length=45)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='students_management.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'db_table': 'audience',
            },
        ),
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('first_name_s', models.CharField(max_length=55, verbose_name='Имя')),
                ('last_name_s', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('phone_number_s', models.CharField(max_length=55, verbose_name='Телефон')),
                ('paid_check', models.CharField(max_length=20, verbose_name='Статус оплаты')),
                ('parents_phone_number', models.CharField(max_length=55, verbose_name='Телефон родителей')),
                ('joined_date', models.DateField(verbose_name='Дата присоединения')),
                ('archived_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата архивирования')),
                ('comments', models.CharField(choices=[('окончил(а) курс', 'Окончил(а) Курс'), ('прекратил(а) обучение', 'Прекратил(а) обучение')], max_length=45)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_students', to='students_management.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Архивированный студент',
                'verbose_name_plural': 'Архивированные студенты',
                'db_table': 'archived_student',
            },
        ),
        migrations.CreateModel(
            name='ArchivedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_pay', models.CharField(max_length=55, verbose_name='Метод оплаты')),
                ('date_pay', models.DateField(verbose_name='Дата оплаты')),
                ('price', models.CharField(max_length=69, verbose_name='Сумма')),
                ('archived_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата архивирования')),
                ('comments', models.CharField(choices=[('окончил(а) курс', 'Окончил(а) Курс'), ('прекратил(а) обучение', 'Прекратил(а) обучение')], max_length=45)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_management.archivedstudent', verbose_name='Студент')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_payments', to='students_management.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Архивированный платеж',
                'verbose_name_plural': 'Архивированные платежи',
                'db_table': 'archived_payment',
            },
        ),
        migrations.CreateModel(
            name='ArchivedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('name_group', models.CharField(max_length=45, verbose_name='Название группы')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('teacher_name', models.CharField(max_length=90, verbose_name='Преподаватель')),
                ('audience_number', models.CharField(max_length=45, verbose_name='Аудитория')),
                ('status_group', models.CharField(max_length=45, verbose_name='Статус группы')),
                ('archived_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата архивирования')),
                ('comments', models.CharField(choices=[('окончил(а) курс', 'Окончил(а) Курс'), ('прекратил(а) обучение', 'Прекратил(а) обучение')], max_length=45)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_groups', to='students_management.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Архивированная группа',
                'verbose_name_plural': 'Архивированные группы',
                'db_table': 'archived_group',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=55)),
                ('price_course', models.CharField(max_length=55)),
                ('duration', models.CharField(max_length=55)),
                ('img_course', models.ImageField(upload_to='course')),
                ('slug_course', models.CharField(max_length=55)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students_management.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_s', models.CharField(max_length=55)),
                ('last_name_s', models.CharField(max_length=55)),
                ('phone_number_s', models.CharField(max_length=55)),
                ('paid_check', models.CharField(choices=[('Оплатил', 'Оплатил'), ('Не оплатил', 'Не оплатил')], default='Не оплатил', max_length=20)),
                ('parents_phone_number', models.CharField(max_length=55)),
                ('joined_date', models.DateField(default=datetime.datetime.today)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students_management.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_pay', models.CharField(choices=[('наличными', 'Наличными'), ('click', 'Click'), ('терминал', 'Терминал')], default='', max_length=55)),
                ('date_pay', models.DateField(default=datetime.datetime.today)),
                ('price', models.CharField(default='', max_length=69)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students_management.branch', verbose_name='Филиал')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_management.student')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'db_table': 'payment',
                'ordering': ('-date_pay',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('audience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_management.audience')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='students_management.branch', verbose_name='Филиал')),
                ('status_group', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='students_management.status')),
                ('students_id', models.ManyToManyField(related_name='students', to='students_management.student')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attendance', models.DateField()),
                ('attendance_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_management.attendance_status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students_management.branch', verbose_name='Филиал')),
                ('groups_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_management.group')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_management.student')),
            ],
            options={
                'verbose_name': 'Посещение студента',
                'verbose_name_plural': 'Посещения студентов',
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('img_teacher', models.ImageField(upload_to='teacher')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='students_management.branch', verbose_name='Филиал')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_management.course')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'teacher',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_management.teacher'),
        ),
    ]
