# Generated by Django 5.0.6 on 2024-06-17 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedstudent',
            options={'ordering': ['archived_date'], 'verbose_name': 'Архивированный студент', 'verbose_name_plural': 'Архивированные студенты'},
        ),
        migrations.AlterModelOptions(
            name='audience',
            options={'ordering': ['number_audience'], 'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name_course'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['status_group'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name_s'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='group',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students_management.course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students_management.course'),
            preserve_default=False,
        ),
    ]
